'use client'

import { useEffect, useRef } from 'react'
import { usePathname, useSearchParams } from 'next/navigation'

export default function AnalyticsTracker() {
  const pathname = usePathname()
  const searchParams = useSearchParams()
  const pageLoadTime = useRef<number>(Date.now())
  const visitorIdRef = useRef<string | null>(null)
  const sessionIdRef = useRef<string | null>(null)

  useEffect(() => {
    // Skip tracking in admin panel
    if (pathname.startsWith('/admin')) {
      return
    }

    // Get or create visitor ID and session ID from localStorage
    if (typeof window !== 'undefined') {
      let visitorId = localStorage.getItem('visitorId')
      let sessionId = sessionStorage.getItem('sessionId')

      if (!visitorId) {
        // Will be generated by server based on IP + UserAgent
        visitorId = null
      }

      if (!sessionId) {
        sessionId = null
      }

      visitorIdRef.current = visitorId
      sessionIdRef.current = sessionId
    }

    // Track page view
    trackPageView(false)

    // Track exit when leaving page
    return () => {
      trackPageView(true)
    }
  }, [pathname, searchParams])

  const trackPageView = async (isExit: boolean) => {
    try {
      const page = pathname + (searchParams.toString() ? `?${searchParams.toString()}` : '')
      const referrer = typeof document !== 'undefined' ? document.referrer : ''

      // Extract UTM parameters
      const utm = {
        source: searchParams.get('utm_source') || undefined,
        medium: searchParams.get('utm_medium') || undefined,
        campaign: searchParams.get('utm_campaign') || undefined,
        term: searchParams.get('utm_term') || undefined,
        content: searchParams.get('utm_content') || undefined,
      }

      // Calculate time spent on page
      const duration = isExit
        ? Math.round((Date.now() - pageLoadTime.current) / 1000)
        : undefined

      // Get screen dimensions
      const screenWidth = typeof window !== 'undefined' ? window.screen.width : undefined
      const screenHeight = typeof window !== 'undefined' ? window.screen.height : undefined

      const response = await fetch('/api/track', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          page,
          referrer: referrer || null,
          sessionId: sessionIdRef.current,
          visitorId: visitorIdRef.current,
          utm,
          screenWidth,
          screenHeight,
          duration,
          exitPage: isExit,
        }),
        // Use keepalive for exit tracking
        ...(isExit ? { keepalive: true } : {}),
      })

      if (response.ok) {
        const data = await response.json()

        // Store visitor ID and session ID
        if (typeof window !== 'undefined' && data.success) {
          if (data.visitorId) {
            localStorage.setItem('visitorId', data.visitorId)
            visitorIdRef.current = data.visitorId
          }

          if (data.sessionId) {
            sessionStorage.setItem('sessionId', data.sessionId)
            sessionIdRef.current = data.sessionId
          }
        }
      }

      // Reset page load time for next page
      if (!isExit) {
        pageLoadTime.current = Date.now()
      }
    } catch (error) {
      // Silently fail - don't disrupt user experience
      console.error('Analytics tracking failed:', error)
    }
  }

  return null // This component doesn't render anything
}
