/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'service-types': ServiceType;
    services: Service;
    products: Product;
    projects: Project;
    'team-members': TeamMember;
    testimonials: Testimonial;
    blog: Blog;
    'contact-inquiries': ContactInquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'service-types': ServiceTypesSelect<false> | ServiceTypesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types".
 */
export interface ServiceType {
  id: number;
  /**
   * e.g., AI & ML Development, Web Development, etc.
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., ai-ml, web-dev)
   */
  slug: string;
  /**
   * Brief description of this service type
   */
  description?: string | null;
  /**
   * Icon or image representing this service type
   */
  icon?: (number | null) | Media;
  /**
   * Hex color code for UI theming (e.g., #FF6B6B)
   */
  color?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  /**
   * Primary service type/category
   */
  serviceType: number | ServiceType;
  /**
   * Brief description (max 200 characters) for cards and previews
   */
  shortDescription: string;
  /**
   * Detailed service description with formatting
   */
  fullDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Service icon or image
   */
  icon?: (number | null) | Media;
  /**
   * Key features or benefits of this service
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Technologies or tools used for this service
   */
  technologies?:
    | {
        technology: string;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    /**
     * Starting price (optional)
     */
    startingPrice?: number | null;
    pricingModel?: ('fixed' | 'hourly' | 'project' | 'custom') | null;
  };
  /**
   * Feature this service on the homepage
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * e.g., HRM System, Accounting Software, etc.
   */
  name: string;
  /**
   * URL-friendly version of the product name
   */
  slug: string;
  /**
   * Product category
   */
  category:
    | 'hrm'
    | 'accounting'
    | 'crm'
    | 'erp'
    | 'project-management'
    | 'inventory'
    | 'pos'
    | 'ecommerce-platform'
    | 'lms'
    | 'business-intelligence'
    | 'other';
  /**
   * Short catchy tagline (e.g., "Simplify Your HR Operations")
   */
  tagline?: string | null;
  /**
   * Brief description for cards and previews (max 200 characters)
   */
  shortDescription: string;
  /**
   * Detailed product description with formatting
   */
  fullDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Product logo
   */
  logo?: (number | null) | Media;
  /**
   * Main product image or screenshot
   */
  featuredImage?: (number | null) | Media;
  /**
   * Product screenshots and images
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Key features and capabilities
   */
  features?:
    | {
        title: string;
        description?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Product modules or components
   */
  modules?:
    | {
        /**
         * Module name (e.g., Payroll, Attendance, Leave Management)
         */
        name: string;
        description?: string | null;
        /**
         * Included in base package
         */
        included?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Technologies used to build this product
   */
  technologies?:
    | {
        technology: string;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    plans?:
      | {
          /**
           * Plan name (e.g., Basic, Professional, Enterprise)
           */
          name: string;
          /**
           * Price amount
           */
          price: number;
          /**
           * Currency code (e.g., USD, EUR, BDT)
           */
          currency?: string | null;
          billingPeriod?: ('monthly' | 'yearly' | 'one-time' | 'custom') | null;
          features?:
            | {
                feature: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Mark as most popular plan
           */
          popular?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Offer custom pricing for enterprises
     */
    customPricingAvailable?: boolean | null;
    freeTrial?: {
      available?: boolean | null;
      /**
       * Trial duration in days
       */
      duration?: number | null;
    };
  };
  /**
   * Key benefits for customers
   */
  benefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  targetAudience?:
    | {
        /**
         * e.g., Small Businesses, Enterprises, Startups
         */
        audience: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Third-party integrations supported
   */
  integrations?:
    | {
        name: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  demo?: {
    /**
     * Demo available
     */
    available?: boolean | null;
    /**
     * Demo URL
     */
    url?: string | null;
    /**
     * Demo video URL (YouTube, Vimeo, etc.)
     */
    videoUrl?: string | null;
  };
  documentation?: {
    /**
     * Documentation URL
     */
    url?: string | null;
    /**
     * User guide PDF
     */
    userGuide?: (number | null) | Media;
  };
  support?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Support hours (e.g., 24/7, 9 AM - 5 PM)
     */
    hours?: string | null;
  };
  /**
   * Current product version
   */
  version?: string | null;
  /**
   * Product release or launch date
   */
  releaseDate?: string | null;
  /**
   * Last update date
   */
  lastUpdate?: string | null;
  /**
   * Version history and changes
   */
  changelog?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Projects using this product
   */
  relatedProjects?: (number | Project)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
  };
  /**
   * Feature this product on homepage
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  status: 'draft' | 'published' | 'coming-soon' | 'retired';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  /**
   * Client or company name
   */
  client: string;
  /**
   * Services provided for this project
   */
  serviceType?: (number | Service)[] | null;
  /**
   * Brief project summary (max 250 characters)
   */
  summary: string;
  /**
   * Detailed project description, challenges, and solutions
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main project image
   */
  featuredImage: number | Media;
  /**
   * Additional project images
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Technologies, frameworks, and tools used
   */
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Project outcomes and metrics
   */
  results?: {
    metrics?:
      | {
          /**
           * e.g., "Performance Improvement", "User Growth"
           */
          label: string;
          /**
           * e.g., "50%", "10,000+ users"
           */
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Live project URL (if applicable)
   */
  projectUrl?: string | null;
  duration?: {
    startDate?: string | null;
    completionDate?: string | null;
  };
  /**
   * Number of team members involved
   */
  teamSize?: number | null;
  /**
   * Feature this project on the homepage
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Job title or role
   */
  position: string;
  department?: ('leadership' | 'ai-ml' | 'development' | 'design' | 'pm' | 'sales' | 'support') | null;
  /**
   * Professional biography
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief bio for team cards (max 150 characters)
   */
  shortBio?: string | null;
  /**
   * Professional headshot
   */
  photo?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
  };
  social?: {
    /**
     * LinkedIn profile URL
     */
    linkedin?: string | null;
    /**
     * Twitter/X profile URL
     */
    twitter?: string | null;
    /**
     * GitHub profile URL
     */
    github?: string | null;
    /**
     * Personal website URL
     */
    website?: string | null;
  };
  /**
   * Key skills and expertise
   */
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Notable achievements or certifications
   */
  achievements?:
    | {
        achievement: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  /**
   * Client company or organization
   */
  company?: string | null;
  /**
   * Client job title
   */
  position?: string | null;
  /**
   * Testimonial text
   */
  content: string;
  /**
   * Rating out of 5 stars
   */
  rating?: number | null;
  /**
   * Client photo or logo
   */
  photo?: (number | null) | Media;
  /**
   * Related project (optional)
   */
  project?: (number | null) | Project;
  /**
   * Related service (optional)
   */
  service?: (number | null) | Service;
  /**
   * YouTube or Vimeo video testimonial URL
   */
  videoUrl?: string | null;
  /**
   * Feature this testimonial on homepage
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  status: 'draft' | 'published';
  /**
   * Date testimonial was received
   */
  dateReceived?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  /**
   * Article author
   */
  author: number | User;
  /**
   * Brief article summary (max 300 characters)
   */
  excerpt: string;
  /**
   * Full article content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main article image
   */
  featuredImage?: (number | null) | Media;
  /**
   * Article category
   */
  category:
    | 'ai-ml'
    | 'web-dev'
    | 'mobile'
    | 'automation'
    | 'case-studies'
    | 'insights'
    | 'trends'
    | 'tutorials'
    | 'news';
  /**
   * Article tags for better searchability
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Related services mentioned in the article
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Related projects mentioned in the article
   */
  relatedProjects?: (number | Project)[] | null;
  seo?: {
    /**
     * SEO title (defaults to article title if empty)
     */
    metaTitle?: string | null;
    /**
     * SEO meta description (max 160 characters)
     */
    metaDescription?: string | null;
    /**
     * SEO keywords (comma-separated)
     */
    keywords?: string | null;
  };
  /**
   * Estimated read time in minutes
   */
  readTime?: number | null;
  /**
   * Feature this article on homepage
   */
  featured?: boolean | null;
  /**
   * Article publication date
   */
  publishedDate?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  name: string;
  /**
   * Contact email address
   */
  email: string;
  /**
   * Contact phone number (optional)
   */
  phone?: string | null;
  /**
   * Company or organization name (optional)
   */
  company?: string | null;
  /**
   * Services interested in
   */
  serviceInterest?: (number | Service)[] | null;
  projectType?: ('new-project' | 'consulting' | 'support' | 'partnership' | 'other') | null;
  /**
   * Estimated project budget
   */
  budget?: ('under-5k' | '5k-10k' | '10k-25k' | '25k-50k' | '50k-plus' | 'unsure') | null;
  /**
   * Desired project timeline
   */
  timeline?: ('urgent' | '1-3-months' | '3-6-months' | '6-plus-months' | 'flexible') | null;
  /**
   * Inquiry message or project details
   */
  message: string;
  /**
   * How did they hear about us?
   */
  source?: ('search' | 'social' | 'referral' | 'ad' | 'direct' | 'other') | null;
  /**
   * Inquiry status for tracking
   */
  status:
    | 'new'
    | 'in-progress'
    | 'contacted'
    | 'qualified'
    | 'proposal-sent'
    | 'converted'
    | 'not-interested'
    | 'closed';
  /**
   * Team member assigned to this inquiry
   */
  assignedTo?: (number | null) | User;
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  /**
   * Internal notes (not visible to client)
   */
  notes?: string | null;
  /**
   * Scheduled follow-up date
   */
  followUpDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'service-types';
        value: number | ServiceType;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types_select".
 */
export interface ServiceTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  color?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  serviceType?: T;
  shortDescription?: T;
  fullDescription?: T;
  icon?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        startingPrice?: T;
        pricingModel?: T;
      };
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  tagline?: T;
  shortDescription?: T;
  fullDescription?: T;
  logo?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  modules?:
    | T
    | {
        name?: T;
        description?: T;
        included?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        plans?:
          | T
          | {
              name?: T;
              price?: T;
              currency?: T;
              billingPeriod?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              popular?: T;
              id?: T;
            };
        customPricingAvailable?: T;
        freeTrial?:
          | T
          | {
              available?: T;
              duration?: T;
            };
      };
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  targetAudience?:
    | T
    | {
        audience?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  demo?:
    | T
    | {
        available?: T;
        url?: T;
        videoUrl?: T;
      };
  documentation?:
    | T
    | {
        url?: T;
        userGuide?: T;
      };
  support?:
    | T
    | {
        email?: T;
        phone?: T;
        hours?: T;
      };
  version?: T;
  releaseDate?: T;
  lastUpdate?: T;
  changelog?: T;
  relatedProjects?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  serviceType?: T;
  summary?: T;
  description?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  results?:
    | T
    | {
        metrics?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  projectUrl?: T;
  duration?:
    | T
    | {
        startDate?: T;
        completionDate?: T;
      };
  teamSize?: T;
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  department?: T;
  bio?: T;
  shortBio?: T;
  photo?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  social?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        github?: T;
        website?: T;
      };
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        achievement?: T;
        id?: T;
      };
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  company?: T;
  position?: T;
  content?: T;
  rating?: T;
  photo?: T;
  project?: T;
  service?: T;
  videoUrl?: T;
  featured?: T;
  order?: T;
  status?: T;
  dateReceived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedServices?: T;
  relatedProjects?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  readTime?: T;
  featured?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  serviceInterest?: T;
  projectType?: T;
  budget?: T;
  timeline?: T;
  message?: T;
  source?: T;
  status?: T;
  assignedTo?: T;
  priority?: T;
  notes?: T;
  followUpDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}